const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
const INCREASE_ITEM_QTY = 'INCREASE_ITEM_QTY';
const REMOVE_ITEM = 'REMOVE_ITEM';
const RESET_CART = 'RESET_CART';
const INCREASE_LINE_ITEM_COUNT = 'INCREASE_LINE_ITEM_COUNT';
const RESET_LINE_ITEM_COUNT = 'RESET_LINE_ITEM_COUNT';
const ADD_ITEM_TO_TRASH = 'ADD_ITEM_TO_TRASH';

  
const exportedObject = {  ADD_ITEM_TO_CART, ADD_ITEM_TO_TRASH, INCREASE_ITEM_QTY, REMOVE_ITEM, RESET_CART, INCREASE_LINE_ITEM_COUNT, RESET_LINE_ITEM_COUNT }

export default exportedObject